# Generated by Django 5.1.2 on 2024-10-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_posta_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
